version: '3.8'

volumes:
  pgdata:

services:

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
